# ThymeleafConfig에 이미 설정해놓음

spring:
  banner:
    location: banner.txt
  
# ansi를 사용한다고 정의해주면 tomcat으로 실행 시, console에 color가 나옴 
  output:
    ansi:
      enabled: always

server:
  port: 8085

logging:
  level:
    root: warn
    org.springFramework.web : debug
    com.example.demo : info
    
    
# spring.output.ansi.enabled=always



#spring:
#  thymeleaf:
#    cache: false
#    template-resolver-order: 1

#  mvc:
#    view:
#      prefix: src/main/webapp/WEB-INF/views/
#      suffix: .html