# ThymeleafConfig에 이미 설정해놓음

spring:
  banner:
    location: banner.txt



#spring:
#  thymeleaf:
#    cache: false
#    template-resolver-order: 1

#  mvc:
#    view:
#      prefix: src/main/webapp/WEB-INF/views/
#      suffix: .html